# Build Stage
FROM node:20 AS build

WORKDIR /app

# Copy package files first
COPY frontend/package*.json ./

# Clean npm cache and install dependencies freshly
RUN npm cache clean --force
RUN npm install --no-optional
RUN npm rebuild rollup

RUN npm install @rollup/rollup-linux-x64-gnu


# Copy the rest of the frontend
COPY frontend ./

# Build the Vite app
RUN npm run build

# Serve Stage using nginx
FROM nginx:stable-alpine

# Copy built files to nginx html folder
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
